### ISSUE TITLE
Prompt occuring after normal reboot

### ISSUE THREAD

**Issue by JayQ2** [homebysix/install-or-defer#1]
Prompt still occurring after a manual reboot.  Have seen this occurring if a user defers the reboot from the prompt and before forcing a reboot they will reboot on there own not using the "Reboot Now" option. Is there anyway to have the prompt to detect a manual reboot and kill itself?

**Comment by JayQ2** [comment]
Great work by the way.  Other than that everything works like a champ.

**Comment by JayQ2** [comment]
Thanks for the quick response. We have restored and tested your original version and works as expected. Thanks for the quick response! Must have been some tinkering on the script on our side when testing. Thanks!

**Comment by homebysix** [comment]
Glad to hear it!
