### ISSUE TITLE
trigger restart

### ISSUE THREAD

**Issue by JayQ2** [homebysix/install-or-defer#2]
Hey Elliot,

Just a heads up.  Found the following bit while troubleshooting the soft and hard restarts.  Didn't have many ppl reaching the soft and hard and restart threshold but when it did the the jamf notification was not showing.  

Looks like where the helper script are getting created and where the helper plist is pointing to are two different directories on order to launch the notification.

/private/tmp vs. /tmp
```
....

 # Create a jamfHelper script that will be called by a LaunchDaemon.
    cat << EOF > "/private/tmp/$HELPER_SCRIPT"
#!/bin/bash
"$jamfHelper" -windowType "utility" -icon "$LOGO" -title "$MSG_RESTART_HEADING" -description "$MSG_RESTART"
EOF
    chmod +x "/private/tmp/$HELPER_SCRIPT"

....

	<key>Label</key>
	<string>${BUNDLE_ID}_helper</string>
	<key>Program</key>
	<string>/private/tmp/$HELPER_SCRIPT</string>
	<key>ThrottleInterval</key>
	<integer>10</integer>

.....
```

**Comment by homebysix** [comment]
Hi @JayQ2 — Thanks for catching this. I fixed it.

Although I'm not sure why it would matter; on most Macs, /tmp is a symbolic link to /private/tmp. Referencing either one should have the same effect.

Give the new version a try and let me know how it goes.
