### ISSUE TITLE
For OS  10.15 ?

### ISSUE THREAD

**Issue by burakcoskunn** [homebysix/install-or-defer#25]
Hello sir,
First of all, thanks a lot for your time! Is there any possibility to work this script with 10.15?
I just try some testing with my new os.
Thanks a lot.

Script result: Jul 19 14:21:21  install_or_defer.sh[3031] <Notice>: Starting install_or_defer.sh script. Performing validation and error checking...
Jul 19 14:21:21  install_or_defer.sh[3031] <Notice>: [ERROR] This script has been tested through macOS 10.14 only. This Mac has 10.15.
Jul 19 14:21:21  install_or_defer.sh

**Comment by mpanighetti** [comment]
If you want to test this script out in macOS Catalina, just modify your local copy of the script to set 10.15 to the maximum allowed operating system. The relevant line is here:

https://github.com/homebysix/install-or-defer/blob/master/payload/Library/Scripts/install_or_defer.sh#L319

Change `[[ "$OS_MINOR" -gt 14 ]]` to `[[ "$OS_MINOR" -gt 15 ]]` and the script will no longer exit when run in Catalina.

Once we've confirmed that the script works as expected in Catalina, we'll make this change in the master branch in a future script revision. Feel free to pass on feedback for any Catalina issues you run into after removing this version restriction, and we can make any required changes to make the script ready for Catalina.

**Comment by burakcoskunn** [comment]
Thanks a lot for your suggestion! Let me try this.

**Comment by burakcoskunn** [comment]
Tried but get this error now;

Script result: Jul 24 14:56:21  install_or_defer.sh[6199] <Notice>: Starting install_or_defer.sh script. Performing validation and error checking...
Jul 24 14:56:22  install_or_defer.sh[6199] <Notice>: [ERROR] Software update catalog can not be reached.
Jul 24 14:56:22  install_or_defer.sh[6199] <Notice>: Stopping due to errors.

I will update you if i can fix.

**Comment by mpanighetti** [comment]
Resolved in #34.
