### ISSUE TITLE
unload LaunchD doesn't finish script?

### ISSUE THREAD

**Issue by master-vodawagner** [homebysix/install-or-defer#28]
Not sure if I'm being stupid here but when I test the script and get to this section on lines 264-279

# Ends script without applying any system updates.
exit_without_updating () {

    echo "Running jamf recon..."
    "$JAMF_BINARY" recon

    clean_up

    if [[ -e "/private/tmp/$BUNDLE_ID.plist" ]]; then
      "/bin/echo" "Unloading $BUNDLE_ID LaunchDaemon..."
      "/bin/launchctl" unload -w "/private/tmp/$BUNDLE_ID.plist"
    fi
    "/bin/echo" "Script will end here."
    exit 0

}

I get the "Unloading" echo prompt but never the "Script will end here" prompt.  Is this because daemon running the script is unloaded so cannot finish off lines 275-279?

**Comment by homebysix** [comment]
Yes, I believe it's actually the `launchctl unload` that kills off the script. The `echo` and `exit` are just in case (and could very well be removed, but cause no harm as is).
