### ISSUE TITLE
Catalina - Software update -list has different arguments for reboot or recommended

### ISSUE THREAD

**Issue by master-vodawagner** [homebysix/install-or-defer#32]
Looks like if you want this to work with Catalina you need to change the search arguments for software update -list to the following

Line 119 
if [[ "$UPDATE_CHECK" == *"[restart]"* ]]

Should become
if [[ "$UPDATE_CHECK" == *"Action: restart"* ]]

Line 126
elif [[ "$UPDATE_CHECK" == *"[recommended]"* ]]

Should become

elif [[ "$UPDATE_CHECK" == *Recommended: YES”* ]]

<img width="770" alt="Screenshot 2019-09-27 at 17 10 18" src="https://user-images.githubusercontent.com/39089724/65791525-d72e8580-e159-11e9-9ad1-0e5d96455af4.png">

**Comment by mpanighetti** [comment]
Thanks! Not sure if we want to wait for the GM to confirm the new wording is still in use, but this should be a simple change to make once Catalina is supported.

**Comment by master-vodawagner** [comment]
Looks like the changes are permanent now

Title: macOS Catalina Developer Beta, Version: 1, Size: 4765007K, Recommended: YES, Action: restart,

**Comment by mpanighetti** [comment]
Resolved in #34.
